# Generated by Django 5.2.4 on 2025-07-04 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_response', models.PositiveIntegerField(blank=True, help_text='Tiempo (segundos) desde que recibió la notificación hasta que respondió', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Emparejamiento',
                'verbose_name_plural': 'Emparejamientos',
            },
        ),
        migrations.CreateModel(
            name='PairingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
