# Generated by Django 5.2.4 on 2025-07-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='trips.publication'),
        ),
    ]
