# Generated by Django 5.2.4 on 2025-07-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pairing',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pairingstatus'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['status_id'], name='core_pairin_status__2ed99b_idx'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['publication_id', 'user_id'], name='core_pairin_publica_4070dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together={('publication_id', 'user_id')},
        ),
    ]
