# Generated by Django 5.2.4 on 2026-02-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='publication_id',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PairingStatus',
        ),
        migrations.DeleteModel(
            name='Pairing',
        ),
    ]
