# Generated by Django 5.2.4 on 2026-01-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
    ]
