# Generated by Django 5.2.4 on 2026-01-10 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('trips', '0003_alter_publication_departure_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='passenger_id',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='publication_id',
            new_name='publication',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('publication', 'passenger')},
        ),
    ]
