# Generated by Django 5.2.4 on 2026-01-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_options_rename_driver_id_chat_driver_and_more'),
        ('trips', '0003_alter_publication_departure_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trip_passenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='trips.trippassenger'),
        ),
    ]
