# Generated by Django 5.2.4 on 2026-01-13 19:42

from django.db import migrations

def migrate_chats(apps, schema_editor):
    Chat = apps.get_model('chat', 'Chat')
    Trip = apps.get_model('trips', 'Trip')
    TripPassenger = apps.get_model('trips', 'TripPassenger')
    TripStatus = apps.get_model('trips', 'TripStatus')
    TripPassengerStatus = apps.get_model('trips', 'TripPassengerStatus')

    # Get or create statuses (safe lookup)
    # We use filter().first() to avoid crashing if table is empty or multiple
    pending_trip = TripStatus.objects.filter(name='Pendiente').first()
    if not pending_trip:
        pending_trip = TripStatus.objects.create(name='Pendiente')
        
    pending_passenger = TripPassengerStatus.objects.filter(name='Pendiente').first()
    if not pending_passenger:
        pending_passenger = TripPassengerStatus.objects.create(name='Pendiente')

    for chat in Chat.objects.all():
        if chat.trip_passenger:
            continue

        # Get or create Trip for the publication
        trip, created = Trip.objects.get_or_create(
            publication_id=chat.publication_id,
            defaults={
                'driver_id': chat.driver_id,
                'status_id': pending_trip.id
            }
        )

        # Get or create TripPassenger
        trip_passenger, tp_created = TripPassenger.objects.get_or_create(
            trip_id=trip.id,
            passenger_id=chat.passenger_id,
            defaults={
                'seats_reserved': 1,
                'status_id': pending_passenger.id
            }
        )

        chat.trip_passenger = trip_passenger
        chat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_trip_passenger'),
        ('trips', '0003_alter_publication_departure_place_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_chats),
    ]
