[pytest]
DJANGO_SETTINGS_MODULE = UniRide.settings.local

addopts =
    --nomigrations
    --cov=apps
    --cov-report=html
    --cov-report=term-missing
    --cov-report=xml
    -v
    --tb=short

python_files = test_*.py tests_*.py
python_classes = Test* *TestCase
python_functions = test_*