# Generated by Django 5.2.4 on 2025-07-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reviewed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['reviewed_id'], name='ratings_rat_reviewe_84363b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['trip_id'], name='ratings_rat_trip_id_bd3d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('trip_id', 'reviewer_id', 'reviewed_id')},
        ),
    ]
