# Generated by Django 5.2.4 on 2025-07-16 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Datos adicionales relevantes', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Usuario sobre el que se actuó, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='Nombre del evento auditado, ej: LOGIN_EXITOSO', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivo de la acción (si aplica)', null=True),
        ),
    ]
