# Generated by Django 5.2.4 on 2025-07-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_auditlog_options_remove_auditlog_admin_id_and_more'),
        ('users', '0003_user_is_verified_pendinguser'),
    ]

    operations = [
    ]
