# Generated by Django 5.2.4 on 2025-07-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
    ]
