# Generated by Django 5.2.4 on 2025-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pendinguser_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
