# Generated by Django 5.2.4 on 2025-07-22 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pendinguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que hizo el preregistro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_preregistrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
