# Generated by Django 5.2.4 on 2025-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_pendinguser_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
