# Generated by Django 5.2.4 on 2025-12-04 15:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_pendinguser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures/'),
        ),
    ]
