# Generated by Django 5.2.4 on 2026-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_pendinguser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuspension',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
