# Generated by Django 5.2.4 on 2026-02-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0004_trip_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('MUNI_TO_U', 'Municipio → Universidad'), ('U_TO_MUNI', 'Universidad → Municipio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='match.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_info', to='trips.publication')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.route')),
                ('closest_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.routepoint')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='trips.publication')),
                ('passenger_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.publication')),
            ],
            options={
                'unique_together': {('driver_publication', 'passenger_publication')},
            },
        ),
    ]
