# Generated by Django 5.2.4 on 2025-07-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehicle'),
        ),
        migrations.AddField(
            model_name='publication',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.publicationtype'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='publication_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.publication'),
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.trippassengerstatus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.tripstatus'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['departure_datetime'], name='trips_publi_departu_2e6136_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['destination'], name='trips_publi_destina_31f95d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trippassenger',
            unique_together={('trip_id', 'passenger_id')},
        ),
    ]
