# Generated by Django 5.2.4 on 2025-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='departure_place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='destination',
            field=models.CharField(max_length=500),
        ),
    ]
