# Generated by Django 5.2.4 on 2026-01-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_publication_departure_place_and_more'),
        ('users', '0014_alter_pendinguser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='users.vehicle'),
        ),
    ]
