# Generated by Django 5.2.4 on 2026-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
