# Generated by Django 5.2.4 on 2026-01-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_driver_finalized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_cancellation_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trippassenger',
            name='cancellation_ack',
            field=models.BooleanField(default=False),
        ),
    ]
