# Generated by Django 5.2.4 on 2026-02-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_canceled_by_trip_driver_cancellation_ack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
